### ISSUE TITLE
TypeError: invalid 'in' operand e

### ISSUE THREAD

**Issue by Rudloff** [toporchillo/jQuery-year-calendar#2]
Hello,

I am trying to use jQuery-year-calendar with jQuery 1.10.2 and jQuery Mobile 1.3.2, and I get this error: `TypeError: invalid 'in' operand e`

My code is simply this:

``` js
/*global $*/
/*jslint browser: true */

$(document).bind('pageshow', function () {
    'use strict';
    $("#calendar-holder").year_calendar();
});

```

**Comment by toporchillo** [comment]
I don't know yet. There are no error with  jQuery 1.8.3, but error with newer versions. Let's find that bug.

**Comment by toporchillo** [comment]
Fixed: https://github.com/toporchillo/jQuery-year-calendar/commit/5a4e25287acf490a7b48f4398df4ba747ca7d2cb
